name: Build por lenguaje

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      language:
        description: "Lenguaje a escoger"
        required: true
        type: choice
        options:
        - Java
        - Node
        - Python
        - PHP
        - Ruby

jobs:
    install-dependencies:
        uses: RamsesMatosCleverIT/Actions1/.github/workflows/action${{ github.event.inputs.language }}.yml@main